# this script parses dump file generated by objdump, 
# and summarizes memory usage for various segments
# see ram_dump.cmd for the cmd.exe script which uses this script
# 
# gawk -f odu.ram.awk odu.dump.out
# 04000C08 .data            1024 impure_data
{  num_lines++; 
   if ((($2 == ".data") || ($2 == ".bss")) && ($3 > 1000)) printf("%-5s  %5u  %s\n", $2, $3, $4) ;
}

